### Add TensorFlow Depenciese

In [8]:
%AddDeps org.platanios tensorflow_2.12 0.1.0-SNAPSHOT --repository https://oss.sonatype.org/content/repositories/snapshots
%AddDeps org.platanios tensorflow_2.12 0.1.0-SNAPSHOT --classifier linux-cpu-x86_64 --repository https://oss.sonatype.org/content/repositories/snapshots

println("Current Scala Version: " , util.Properties.versionString)

Marking org.platanios:tensorflow_2.12:0.1.0-SNAPSHOT for download
Preparing to fetch from:
-> file:/tmp/toree-tmp-dir3385205836966184036/toree_add_deps/
-> https://oss.sonatype.org/content/repositories/snapshots
-> https://repo1.maven.org/maven2
Marking org.platanios:tensorflow_2.12:0.1.0-SNAPSHOT for download
Preparing to fetch from:
-> file:/tmp/toree-tmp-dir3385205836966184036/toree_add_deps/
-> https://oss.sonatype.org/content/repositories/snapshots
-> https://repo1.maven.org/maven2
(Current Scala VErsion: ,version 2.11.8)


# Tensors

In [1]:
%%pyspark
import tensorflow as tf

2017-10-01 20:28:43.121448: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-01 20:28:43.121477: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-01 20:28:43.121482: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-10-01 20:28:43.121486: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-01 20:28:43.121489: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't

In [2]:
import org.platanios.tensorflow.api._
import org.platanios.tensorflow.api.ops.variables.ConstantInitializer

logger = com.typesafe.scalalogging.Logger@29f378f8


com.typesafe.scalalogging.Logger@29f378f8

In [3]:
val session = tf.Session()

session = Session(org.platanios.tensorflow.api.core.Graph$Reference@5eccc2c8,140683471779584)


Session(org.platanios.tensorflow.api.core.Graph$Reference@5eccc2c8,140683471779584)

In [18]:
%%pyspark
import tensorflow as tf
import numpy as np

In [1]:
%%pyspark
sess = tf.Session()
my_tensor = tf.zeros([3,4])
sess.run(my_tensor)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]

In [2]:
val myTensor = tf.zeros(Shape(3, 4), INT32)
//We can evaluate tensors with calling a run() method on our session.
session.run(fetches = myTensor).toString

myTensor = Output(name = Zeros_2:0, shape = [3, 4], dataType = INT32)


INT32[3, 4]

In [3]:
session.run(fetches = myTensor).summarize()

INT32[3, 4]
[[0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0]]

In [40]:
//TensorFlow algorithms need to know which objects are variables and which are constants.
val myVar = tf.variable("myVar", FLOAT32, Shape(3, 4), tf.zerosInitializer)

//Note that you can not run sess.run(my_var), this would result in an error.
// Because TensorFlow operates with computational graphs, we have to create a variable
// intialization operation in order to evaluate variables.
// We will see more of this later on. For this script,
// we can initialize one variable at a time by calling the variable method my_var.initializer.
session.run(targets = myVar.initializer)
session.run(fetches = myVar.value).summarize()

myVar = myVar


FLOAT32[3, 4]
[[0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0]]

In [38]:
val fillVar = tf.variable("fillVar", FLOAT32,  Shape(4,4), initializer=ConstantInitializer(-1))
session.run(targets = fillVar.initializer)
session.run(fetches = fillVar.value).summarize()

fillVar = fillVar


FLOAT32[4, 4]
[[-1.0, -1.0, -1.0, -1.0],
 [-1.0, -1.0, -1.0, -1.0],
 [-1.0, -1.0, -1.0, -1.0],
 [-1.0, -1.0, -1.0, -1.0]]

In [14]:
%%pyspark
rnorm_var = tf.random_normal([4, 4], mean=0.0, stddev=1.0)
runif_var = tf.random_uniform([4, 4], minval=0, maxval=4)
# //For some reason python print is not getting printed, hence now print in following line
sess.run(rnorm_var), sess.run(runif_var)

(array([[-0.828915  , -0.50810468, -1.04087484, -0.87839603],
       [-2.45272708, -1.00814497,  0.45904839,  0.75511128],
       [-0.72185045, -0.56020445,  0.85645306, -1.8109163 ],
       [-0.45914441, -0.28174588,  0.60512108, -1.82534993]], dtype=float32), array([[ 3.70811415,  1.14646053,  3.12337112,  1.07430506],
       [ 0.71988201,  3.74687433,  2.47542191,  3.07459593],
       [ 2.95685101,  2.33427668,  3.21082687,  1.55605984],
       [ 3.3607049 ,  1.04114008,  1.14327908,  3.55917978]], dtype=float32))

In [36]:
//Random number Tensors
val randomNormalizedTensor = tf.randomNormal(shape=Shape(3,3))
session.run(fetches = randomNormalizedTensor).toString

randomNormalizedTensor = Output(name = RandomNormal_5/Add:0, shape = [3, 3], dataType = FLOAT32)


FLOAT32[3, 3]

In [37]:
session.run(fetches = randomNormalizedTensor).summarize()

FLOAT32[3, 3]
[[-1.4023938, -1.4343731, 0.30504042],
 [-0.28787678, -1.0420817, 0.9471271],
 [-0.77256095, -1.0359018, -0.33004028]]

# PlaceHolders

In [20]:
%%pyspark
x = tf.placeholder(tf.float32, shape=(4, 4))

# //Get graph handle with the tf.Session()
# //Input data to placeholder, note that 'rand_array' and 'x' are the same shape.
rand_array = np.random.rand(4, 4)

# //Create a Tensor to perform an operation (here, y will be equal to x, a 4x4 matrix)
y = tf.identity(x)

# //Print the output, feeding the value of x into the computational graph
sess.run(y, feed_dict={x: rand_array})

[[ 0.02678457  0.38198191  0.65543461  0.59586072]
 [ 0.4504922   0.15288144  0.68403876  0.1298219 ]
 [ 0.64243126  0.93652087  0.29207686  0.51912475]
 [ 0.6084832   0.87546676  0.43247786  0.07193492]]

In [30]:
val x = tf.placeholder(FLOAT64, shape = Shape(3,3))

val y = tf.identity(x)

val tensor2 = Tensor(Tensor(Tensor(2.0), Tensor(0.0), Tensor(5.0)),
                    Tensor(Tensor(1.0), Tensor(4.0), Tensor(7.0)),
                    Tensor(Tensor(56.0), Tensor(-2.0), Tensor(-9.0)))

session.run(targets = tf.globalVariablesInitializer())
val feed_dict = Map(x -> tensor2)
session.run(feeds = feed_dict, fetches = y).summarize()

x = Output(name = Placeholder_1:0, shape = [3, 3], dataType = FLOAT64)
y = Output(name = Identity_1/Identity:0, shape = [3, 3], dataType = FLOAT64)
tensor2 = FLOAT64[3, 3, 1]
feed_dict = Map(Output(name = Placeholder_1:0, shape = [3, 3], dataType = FLOAT64) -> FLOAT64[3, 3, 1])


FLOAT64[3, 3, 1]
[[[2.0],
  [0.0],
  [5.0]],

 [[1.0],
  [4.0],
  [7.0]],

 [[56.0],
  [-2.0],
  [-9.0]]]

# Matrices

In [29]:
%%pyspark
identity_matrix = tf.diag([1.0,2.0,3.0,4.0,5.0])
sess.run(identity_matrix)

[[ 1.  0.  0.  0.  0.]
 [ 0.  2.  0.  0.  0.]
 [ 0.  0.  3.  0.  0.]
 [ 0.  0.  0.  4.  0.]
 [ 0.  0.  0.  0.  5.]]

In [28]:
val identityMatrix = tf.diag(Array(1,2,3,4,5))
session.run(fetches = identityMatrix).summarize()

identityMatrix = Output(name = Diag_1:0, shape = [5, 5], dataType = INT32)


INT32[5, 5]
[[1, 0, 0, 0, 0],
 [0, 2, 0, 0, 0],
 [0, 0, 3, 0, 0],
 [0, 0, 0, 4, 0],
 [0, 0, 0, 0, 5]]

In [24]:
%%pyspark
B = tf.fill([2,3], 5.0)
sess.run(B)

[[ 5.  5.  5.]
 [ 5.  5.  5.]]

In [27]:
val fill = tf.fill(shape = Shape(3,3), 5)
session.run(fetches = fill).summarize()

fill = Output(name = Fill_1:0, shape = [3, 3], dataType = INT32)


INT32[3, 3]
[[5, 5, 5],
 [5, 5, 5],
 [5, 5, 5]]

In [43]:
%%pyspark
C = tf.random_uniform([3,2])
sess.run(C)


[[ 0.51009226  0.7223177 ]
 [ 0.38323283  0.95759487]
 [ 0.96507931  0.47849178]]

In [44]:
val randMatrix = tf.randomUniform(shape = Shape(3,2))
session.run(fetches = randMatrix).summarize()

randMatrix = Output(name = RandomUniform/Add:0, shape = [3, 2], dataType = FLOAT32)


FLOAT32[3, 2]
[[0.2713585, 0.8257055],
 [0.83426976, 0.9168836],
 [0.6829114, 0.8398231]]

In [45]:
val A = tf.fill(shape = Shape(3,3), 3)
val B = tf.fill(shape = Shape(3,3), 2)

A = Output(name = Fill_2:0, shape = [3, 3], dataType = INT32)
B = Output(name = Fill_3:0, shape = [3, 3], dataType = INT32)


Output(name = Fill_3:0, shape = [3, 3], dataType = INT32)

In [47]:
session.run(fetches = A+B).summarize()

INT32[3, 3]
[[5, 5, 5],
 [5, 5, 5],
 [5, 5, 5]]

In [48]:
session.run(fetches = A-B).summarize()

INT32[3, 3]
[[1, 1, 1],
 [1, 1, 1],
 [1, 1, 1]]

In [49]:
session.run(fetches = A*B).summarize()

INT32[3, 3]
[[6, 6, 6],
 [6, 6, 6],
 [6, 6, 6]]

In [50]:
session.run(fetches = tf.matmul(A,B)).summarize()

INT32[3, 3]
[[18, 18, 18],
 [18, 18, 18],
 [18, 18, 18]]

In [51]:
session.run(fetches = tf.transpose(randMatrix)).summarize()

FLOAT32[2, 3]
[[0.36015582, 0.57526064, 0.5414257],
 [0.9038662, 0.3487574, 0.5220282]]